### PR TITLE
Update composer.json

### PR DESCRIPTION
**Pull request by Eddyhotkey**
Update for Contao 5.3

### CODE REVIEW

**Review by fritzmg — APPROVED** [review]

**Comment by fritzmg** [comment]
@Eddyhotkey did you also test it in Contao 5?

**Comment by Eddyhotkey** [comment]
Yes I tried to install this extension on the site. 
Contao version 5.3.7
PHP version 8.2
I get the following errors:
Problem 1
    - menatwork/semantic_html5 2.1.0 requires php ^7.2 -> your php version (8.2.18.0) does not satisfy that requirement.
    - menatwork/semantic_html5 2.1.1 requires contao/core-bundle ^4.4.8 -> found contao/core-bundle[4.4.8, ..., 4.13.43] but these were not loaded, likely because it conflicts with another require.
    - Root composer.json requires menatwork/semantic_html5 ^2.1 -> satisfiable by menatwork/semantic_html5[2.1.0, 2.1.1].

**Comment by fritzmg** [comment]
No, I meant: did you install your fork in Contao 5 and test whether everything still works in Contao 5?

**Comment by fritzmg** [comment]
Then I cannot merge this. You first need to test the extension in Contao 5 and incorporate any adjustments that are necessary for Contao 5 in this PR.

**Review by fritzmg — CHANGES_REQUESTED** [review]
Then I cannot merge this. You first need to test the extension in Contao 5 and incorporate any adjustments that are necessary for Contao 5 in this PR.

**Pull request closed without merging**
